version: "3.7"

services:
  cassandra:
    image: 'docker.io/bitnami/cassandra:3-debian-10'
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

  # rabbitmq:
  #   build: ./rabbitmq
  #   ports:
  #     - '4369:4369'
  #     - '5672:5672'
  #     - '25672:25672'
  #     - '15672:15672'
  #   volumes:
  #     - 'rabbitmq_data:/bitnami'

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  cassandra_data:
    driver: local
